### PR TITLE
Bye Bye

### PR DESCRIPTION
**Pull request by JuanGQCadavid**
I've been analyzing The back and I concluded that It's unnecessary.

### CODE REVIEW

**Comment by fighur** [comment]
Ok, I'll check your request and, if you are correct, I'll merge. 🥇

**Comment by JuanGQCadavid** [comment]
Ok, I'll be waiting for you answered.

**Comment by JuanGQCadavid** [comment]
> Ok, I'll be waiting for you answered.

answer*

**Comment by fighur** [comment]
The request seems alright and passed the tests, so I'll merge it, thank you for your contribution. 👍 💯

**Pull request merged**
